version: '3'

services:    
  mongodb:
    image: "mongo:5.0.3"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongo"
      MONGO_INITDB_ROOT_PASSWORD: "secret"
      MONGO_INITDB_DATABASE: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - sketch_data:/data/db

volumes:
  sketch_data:
