version: '3'

services:
  web:
    build: .
    depends_on: 
      - postgres
    environment:
      PORT: "80"
      POSTGRES_PORT: "5432"
      POSTGRES_HOST: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "8080:80"

  postgres:
    image: "postgres:13"
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "54320:5432"
    volumes:
      - sketch_data:/var/lib/postgresql/data

volumes:
  sketch_data:
